---
title: "HW0"
author: "Jonathan Wilson"
date: "January 5, 2019"
output: word_document
---

#Cntl-alt-i (Creates the rmarkdown blocks)
```{r}
setwd("C:\\Users\\jon\\Documents\\School\\R\\HW\\HW0")
```


```{r}
#Replicate Function
rep(1:9, 3)#1 2 3...9 1 2...9 1..9
rep(5, 10)
```

```{r}
#Sequence Generation
seq(from = 1, to = 9, by = 2)#1,3,5,..9
seq(from = 1, to = 10, by = 2)
```


```{r}
v1 <- seq(from = 1, to = 9, by = 2)
length(v1)
```


```{r}
v1 <- seq(from = 1, to = 9, by = 2)
rev(v1)#Reverse elements
```


#Run this code multiple times and notice the change.
```{r}
sample(1:5, 10, replace = TRUE)#Random Samples and permutations. 
```



#Run this code and notice the change does not occur.
```{r}
set.seed(30)#This is desirable for repoducible results for other researches to check. For Random num generation. If #you want the same number repeditly.
sample(1:5, 10, replace = TRUE)
```



```{r}
samp <- sample(1:5, 10, replace = TRUE)
samp
unique(samp)#Extracts Unique Elements
```



```{r}
set.seed(2)
vec <- sample(seq(1, 100, by = 3), 15, replace = FALSE)
vec
```

```{r}
sort(vec, decreasing = FALSE)
```

#Note the difference between sort() and order().
```{r}
order(vec, decreasing=FALSE)#Orders the "Ramk Number"
```


```{r}
vec <- sample(seq(0, 10, by=0.0001), 5, replace = TRUE)
vec
round(vec, digits = 2)
round(vec)
```



```{r}
vec <- sample(seq(0, 10, by = 0.0001), 10, replace = TRUE)
vec
max(vec) #returns the maximum value
```

```{r}
which.max(vec) #returns the position of the maximum value
```


```{r}
vec <- sample(1:10, 10, replace = TRUE)
vec
median(vec)
mean(vec)
sum(vec)
```

#Note the difference between cbind() and rbind().
```{r}
seq1 <- seq(1, 10, by = 2)
seq2 <- seq(20, 100, by = 20)
cbind(seq1, seq2)
rbind(seq2, rev(seq1))
```


```{r}
data(mtcars) #loads the data
head(mtcars) #returns the beginning of a vector/table/data frame, etc.
tail(mtcars) #returns the last part of a vector/table/data frame, etc.
```


```{r}
dim(mtcars)
nrow(mtcars)
ncol(mtcars)
```